name: InfectionRevamped
version: '${project.version}'
main: grapeapplefruit.main.Main
api-version: 1.18
commands:
  forcestart:
    description: Force start the game.
    permission: op
  leave:
    description: Leave the game.
  join:
    description: Join the game.
